### ISSUE TITLE
Add switch to control parallel execution on invoker

### ISSUE THREAD

**Issue by domdom82** [openwhisk/openwhisk#1123]
At the moment the invoker synchronizes on `dockerOp` and `dockerPull` which serializes docker operations for safety reasons.

With upcoming docker releases this problem is less severe. @perryibm and I have been discussing to add an option that allows you to turn the synchronization on and off:

in group_vars/all:
```
invoker:
  serialize:
    dockerOp: <true|false>
    dockerPull: <true|false> 
```

write to whisk.properties -> read from consul.

Apply in ContainerPool.scala.
